[package]
name = "simple_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_fs = "1.0.7"
env_logger = "0.9.1"
log = "0.4.17"
mockall = "0.11.2"
rand = "0.8.5"
